# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Switch windows with vim keys
bind -n M-H previous-window
bind -n M-L next-window

# Reload config
bind r source ~/.config/tmux/tmux.conf

# Start windows & panes index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

source ~/.config/tmux/tmux.conf.style

# Basic plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Init TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
