#!/bin/sh

sxhkd &
launch_polybar &
xsetroot -cursor_name left_ptr &	# Set cursor to pointer style

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding		20
bspc config focus_follows_pointer true

bspc config focused_border_color 	"#458588"
